### ISSUE TITLE
The reproduction result on vkitti2/Scene18/morning is poor

### ISSUE THREAD

**Issue by heatMa** [OPEN-AIR-SUN/mars#21]
the train cmd is
```
CUDA_VISIBLE_DEVICES="0,1" python nerfstudio/nerfstudio/scripts/train.py  nsg-vkitti-car-depth-recon --data vkitti2/Scene18/morning --pipeline.datamanager.dataparser.car_object_latents_pa
th  pretrain/VituralKITTI2/car-object-latents/latent_codes18.pt --pipeline.datamanager.dataparser.car_nerf_state_dict_path pretrain/VituralKITTI2/car-nerf-state-dict/epoch_805.ckpt --experiment_name reduce_eval --machine.num-gpus
 2
```

**As seen in the video, the sporty car is very blurry**
https://github.com/OPEN-AIR-SUN/mars/assets/18495380/0940157d-a307-4516-a732-4be841f5a805

**the wandb log is [here](https://api.wandb.ai/links/rongbo/jgxg0shd), the psnr seems low**
![image](https://github.com/OPEN-AIR-SUN/mars/assets/18495380/a408165b-ae6a-462f-a379-f08ce9dd95b2)

Could you give some suggestions about how to solve the problem? 
Many thanks!

**Comment by wuzirui** [comment]
As can be seen in the wandb log, the `object_rgb` channel blacks out. Have you checked the correctness of object poses?

**Comment by heatMa** [comment]
I just use the raw vkitti data, and didn't check the data. I think the data have no problem.

This is the [wandb log](https://api.wandb.ai/links/rongbo/or2gkyq2) on `vkitti2/Scene02/15-deg-left`, it's psnr is also lower(near 21, same as vkitti2/Scene18/morning )
![image](https://github.com/OPEN-AIR-SUN/mars/assets/18495380/ee0c75a3-2e2b-450d-b708-73d7b142c0c1)
Below is `vkitti2/Scene06/clone`, the psnr is near 28, it seems good as paper's result. [wandb log](https://api.wandb.ai/links/rongbo/wj3jqvd2) 
![vkitti2/Scene06/clone](https://github.com/OPEN-AIR-SUN/mars/assets/18495380/aac6b96e-d3de-49f7-bf13-6f3bbde78ce8)

Is it possible that ego motion's effect? Ego motion in scene06 is small, while in Scene02 and Scene18 is relatively large.

Do you have the experiment on vkitti2/Scene18 and vkitti2/Scene02? Could you upload your result?

Many thanks!

**Comment by xBeho1der** [comment]
Here is an [wandb log](https://api.wandb.ai/links/wuzirui-research/4akpmoki) of our experiment on vkitti2/Scnen02/clone, below is our experiment config:
```yml
!!python/object:nerfstudio.engine.trainer.TrainerConfig
_target: !!python/name:nerfstudio.engine.trainer.Trainer ''
data: &id003 !!python/object/apply:pathlib.PosixPath
- /
- data
- luoly
- dataset
- demo
- vkitti
- Scene02
- clone
experiment_name: nsg-vkitti-recon-02seq05to220
load_checkpoint: null
load_config: null
load_dir: null
load_step: null
log_gradients: true
logging: !!python/object:nerfstudio.configs.base_config.LoggingConfig
  local_writer: !!python/object:nerfstudio.configs.base_config.LocalWriterConfig
    _target: !!python/name:nerfstudio.utils.writer.LocalWriter ''
    enable: true
    max_log_size: 10
    stats_to_track: !!python/tuple
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Train Iter (time)
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Train Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Test PSNR
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Vis Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Test Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - ETA (time)
  max_buffer_size: 20
  profiler: basic
  relative_log_dir: !!python/object/apply:pathlib.PosixPath []
  steps_per_log: 10
machine: !!python/object:nerfstudio.configs.base_config.MachineConfig
  dist_url: auto
  machine_rank: 0
  num_gpus: 1
  num_machines: 1
  seed: 42
max_num_iterations: 600000
method_name: nsg-vkitti-car-depth-recon
mixed_precision: false
optimizers:
  background_model:
    optimizer: !!python/object:nerfstudio.engine.optimizers.RAdamOptimizerConfig
      _target: &id001 !!python/name:torch.optim.radam.RAdam ''
      eps: 1.0e-15
      lr: 0.001
      max_norm: null
      weight_decay: 0
    scheduler: !!python/object:nerfstudio.engine.schedulers.ExponentialDecaySchedulerConfig
      _target: &id002 !!python/name:nerfstudio.engine.schedulers.ExponentialDecayScheduler ''
      lr_final: 1.0e-05
      lr_pre_warmup: 1.0e-08
      max_steps: 200000
      ramp: cosine
      warmup_steps: 0
  object_model:
    optimizer: !!python/object:nerfstudio.engine.optimizers.RAdamOptimizerConfig
      _target: *id001
      eps: 1.0e-15
      lr: 0.005
      max_norm: null
      weight_decay: 0
    scheduler: !!python/object:nerfstudio.engine.schedulers.ExponentialDecaySchedulerConfig
      _target: *id002
      lr_final: 1.0e-05
      lr_pre_warmup: 1.0e-08
      max_steps: 200000
      ramp: cosine
      warmup_steps: 0
output_dir: !!python/object/apply:pathlib.PosixPath
- outputs
pipeline: !!python/object:nsg.nsg_pipeline.NSGPipelineConfig
  _target: !!python/name:nsg.nsg_pipeline.NSGPipeline ''
  datamanager: !!python/object:nsg.data.nsg_datamanager.NSGkittiDataManagerConfig
    _target: !!python/name:nsg.data.nsg_datamanager.NSGkittiDataManager ''
    camera_optimizer: !!python/object:nerfstudio.cameras.camera_optimizers.CameraOptimizerConfig
      _target: !!python/name:nerfstudio.cameras.camera_optimizers.CameraOptimizer ''
      mode: 'off'
      optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
        _target: !!python/name:torch.optim.adam.Adam ''
        eps: 1.0e-15
        lr: 0.0006
        max_norm: null
        weight_decay: 0
      orientation_noise_std: 0.0
      param_group: camera_opt
      position_noise_std: 0.0
      scheduler: !!python/object:nerfstudio.engine.schedulers.ExponentialDecaySchedulerConfig
        _target: *id002
        lr_final: null
        lr_pre_warmup: 1.0e-08
        max_steps: 10000
        ramp: cosine
        warmup_steps: 0
    camera_res_scale_factor: 1.0
    data: *id003
    dataparser: !!python/object:nsg.data.nsg_vkitti_dataparser.NSGvkittiDataParserConfig
      _target: !!python/name:nsg.data.nsg_vkitti_dataparser.NSGvkitti ''
      add_input_rows: -1
      alpha_color: white
      bckg_only: false
      box_scale: 1.5
      car_nerf_state_dict_path: !!python/object/apply:pathlib.PosixPath
      - /
      - DATA_EDS
      - liuty
      - ckpts
      - pretrain
      - car_nerf
      - vkitti
      - epoch_805.ckpt
      car_object_latents_path: !!python/object/apply:pathlib.PosixPath
      - /
      - DATA_EDS
      - liuty
      - ckpts
      - pretrain
      - car_nerf
      - vkitti
      - latents
      - latent_codes02.pt
      chunk: 32768
      data: !!python/object/apply:pathlib.PosixPath
      - /
      - data1
      - luoly
      - datasets
      - NSGstudio
      - vkitti
      - Scene06
      - clone
      dataset_type: vkitti
      far_plane: 150.0
      first_frame: 5
      last_frame: 220
      max_input_objects: -1
      near_plane: 0.5
      netchunk: 65536
      novel_view: left
      obj_only: false
      obj_opaque: true
      object_setting: 0
      render_only: false
      scale_factor: 0.1
      scene_scale: 2.0
      split_setting: reconstruction
      use_car_latents: true
      use_depth: true
      use_obj: true
      use_object_properties: true
    eval_image_indices: !!python/tuple
    - 0
    eval_num_images_to_sample_from: -1
    eval_num_rays_per_batch: 4096
    eval_num_times_to_repeat_images: -1
    patch_size: 1
    train_num_images_to_sample_from: -1
    train_num_rays_per_batch: 4096
    train_num_times_to_repeat_images: -1
  model: !!python/object:nsg.models.scene_graph.SceneGraphModelConfig
    _target: !!python/name:nsg.models.scene_graph.SceneGraphModel ''
    background_color: last_sample
    background_model: !!python/object:nsg.models.nerfacto.NerfactoModelConfig
      _target: !!python/name:nsg.models.nerfacto.NerfactoModel ''
      background_color: last_sample
      collider_params:
        far_plane: 6.0
        near_plane: 2.0
      disable_scene_contraction: false
      distortion_loss_mult: 0.002
      enable_collider: true
      eval_num_rays_per_chunk: 4096
      far_plane: 150.0
      hidden_dim: 64
      hidden_dim_color: 64
      hidden_dim_transient: 64
      log2_hashmap_size: 19
      loss_coefficients:
        rgb_loss_coarse: 1.0
        rgb_loss_fine: 1.0
      max_res: 2048
      near_plane: 0.05
      num_coarse_samples: 24
      num_levels: 16
      num_nerf_samples_per_ray: 97
      num_proposal_iterations: 2
      num_proposal_samples_per_ray: !!python/tuple
      - 256
      - 128
      obj_feat_dim: 0
      orientation_loss_mult: 0.0001
      pred_normal_loss_mult: 0.001
      predict_normals: false
      proposal_net_args_list:
      - hidden_dim: 16
        log2_hashmap_size: 17
        max_res: 128
        num_levels: 5
        use_linear: false
      - hidden_dim: 16
        log2_hashmap_size: 17
        max_res: 256
        num_levels: 5
        use_linear: false
      proposal_update_every: 5
      proposal_warmup: 5000
      proposal_weights_anneal_max_num_iters: 1000
      proposal_weights_anneal_slope: 10.0
      sampler: proposal
      use_average_appearance_embedding: true
      use_gradient_scaling: false
      use_proposal_weight_anneal: true
      use_same_proposal_network: false
      use_single_jitter: true
    collider_params:
      far_plane: 6.0
      near_plane: 2.0
    debug_object_pose: false
    depth_loss_mode: naive
    depth_loss_mult: 0.01
    depth_weight_mode: fix
    distortion_loss_mult: 0.002
    enable_collider: true
    eval_num_rays_per_chunk: 4096
    far_plane: 1000.0
    interlevel_loss_mult: 1.0
    latent_size: 256
    loss_coefficients:
      rgb_loss_coarse: 1.0
      rgb_loss_fine: 1.0
    max_num_obj: -1
    near_plane: 0.05
    object_model_template: !!python/object:nsg.models.car_nerf.CarNeRFModelConfig
      _target: !!python/name:nsg.models.car_nerf.CarNeRF ''
      background_color: black
      collider_params:
        far_plane: 6.0
        near_plane: 2.0
      enable_collider: true
      eval_num_rays_per_chunk: 4096
      loss_coefficients:
        rgb_loss_coarse: 1.0
        rgb_loss_fine: 1.0
      num_coarse_samples: 32
      num_fine_samples: 97
      optimize_latents: false
    object_ray_sample_strategy: remove-bg
    object_representation: class-wise
    object_warmup_steps: 1000
    orientation_loss_mult: 0.0001
    pred_normal_loss_mult: 0.001
    predict_normals: false
    ray_add_input_rows: -1
    use_interlevel_loss: true
project_name: nerfstudio-project
relative_model_dir: !!python/object/apply:pathlib.PosixPath
- nerfstudio_models
save_only_latest_checkpoint: false
steps_per_eval_all_images: 5000
steps_per_eval_batch: 500
steps_per_eval_image: 500
steps_per_save: 2000
timestamp: 2023-05-30_230718
use_grad_scaler: true
viewer: !!python/object:nerfstudio.configs.base_config.ViewerConfig
  image_format: jpeg
  jpeg_quality: 90
  max_num_display_images: 512
  num_rays_per_chunk: 32768
  quit_on_train_completion: false
  relative_log_filename: viewer_log_filename.txt
  websocket_host: 0.0.0.0
  websocket_port: null
  websocket_port_default: 7007
vis: wandb
```
